config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  root 'welcome#index'
  get 'welcome/index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email,
            presence: true,
            uniqueness: true,
            format: {
                with:  /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
            }

  validates :password,
            length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Sign up successful."
    else
      render "new"
    end
  end

  # call 'show' when user selects to view profile
  def show
  end

  # call 'edit' when user selects to edit profile
  def edit
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Misms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">Sample App</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active">
              <%= link_to "Home", root_path, class: "active" %>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
                <li>Logged in as: <%= current_user.email %></li>
                <li>
                  <%= link_to "Log Out", logout_path, method: 'delete' %>
                </li>
            <% else %>
                <li>
                  <%= link_to "Sign Up", signup_path%>
                </li>
                <li>
                  <%= link_to "Log In", login_path %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}", class: "container" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="container">
    <h1>Sign Up</h1>
    <%= form_for @user, class: 'form' do |f| %>
        <% if @user.errors.any? %>
            <div class="error_messages">
              <h2>Form is invalid</h2>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group field">
          <%= f.label :email %><br />
          <%= f.text_field :email %>
        </div>
        <div class="form-group field">
          <%= f.label :password %><br />
          <%= f.password_field :password %>
        </div>
        <div class="form-group field">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation %>
        </div>
        <div class="form-group actions"><%= f.submit "Submit", class:"btn"%></div>
    <% end %>
</div>

app/views/welcome/index.html.erb
<div class="container">
    <h2>Welcome to Sample App</h2>
</div>